# Generated by Django 3.2.18 on 2023-04-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230407_1937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='IngredientRecipe',
        ),
        migrations.RenameModel(
            old_name='RecipeTag',
            new_name='TagRecipe',
        ),
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'ordering': ('recipe',), 'verbose_name': 'Количество ингредиента', 'verbose_name_plural': 'Количество ингредиентов'},
        ),
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'ordering': ('recipe',), 'verbose_name': 'Тег рецепта', 'verbose_name_plural': 'Теги рецептов'},
        ),
    ]
