# Generated by Django 3.2.18 on 2023-04-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_favorite_unique_favorite_recipe'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='unique_shopping_cart_recipe'),
        ),
    ]
